### ISSUE TITLE
API v4 or v3

### ISSUE THREAD

**Issue by L04DB4L4NC3R** [CodeChefVIT/love-open-source#1]
Which GitHub API should be used? Graph or REST?

**Comment by YashMeh** [comment]
I think v3 will be better because we don't want to target specific queries like 'Which contributor made a commit on Monday at say 5 pm?'
Rather we want 'Who all and how many commits an individual has made on a repo?' for which REST will suffice . :) 

What you say ?

**Comment by L04DB4L4NC3R** [comment]
Makes sense
